FROM gs-worker-host AS worker-host

FROM microsoft/aspnetcore-build:2.0 AS build
COPY . /src
WORKDIR /src/Src/GlobalSearch.Worker.Scheduler

RUN dotnet publish -c Release -o /tmp/app

FROM microsoft/aspnetcore:2.0 AS aspnetcore

FROM aspnetcore AS final
WORKDIR /app

COPY --from=worker-host /app .
COPY --from=build /tmp/app .
COPY --from=build /src/Src/GlobalSearch.Worker.Scheduler/appsettings.json .

ENTRYPOINT ["dotnet", "Cloud.WorkerHost.dll"]