FROM gs-worker-host AS build

WORKDIR /src/Src/GlobalSearch.Worker.Replay.Executor
RUN dotnet publish -c Release -o /tmp/app

FROM build AS final
WORKDIR /app

COPY --from=build /tmp/app .
COPY --from=build /src/Src/GlobalSearch.Worker.Replay.Executor/appsettings.json .

ENTRYPOINT ["dotnet", "Cloud.WorkerHost.dll"]