apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "gs.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "gs.fullname" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "gs.fullname" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: gs-elasticsearch
          image: elasticsearch:5.6.8
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9200
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http